Repository likelion-plus/counting-stars-13, pull requests merged in 2023-11, with the labels that each got.

#20 Brand, Shop, Detail 페이지 만들었습니다.
  public/cancel.png
  public/cart.png
  public/eventBanner.png
  public/like.png
  public/pagination1.png
  public/pagination2.png
  public/productMore.png
  public/reviewSwiperArrow.png
  public/swiperArrow.png
  src/components/BestItem.tsx
  src/components/BrandIntroduce.tsx
  src/components/Logo.tsx
  src/components/MainTitle.tsx
  src/components/PageMap.tsx
  src/components/ProductContainer.tsx
  src/components/ProductItem.tsx
  src/components/ProductOption.tsx
  src/components/ReviewItem.tsx
  src/components/ReviewSlide.tsx
  src/components/SlideBanner.tsx
  src/components/Slogan.tsx
  src/pages/Brand.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/Shop.tsx
  src/styles/reviewSlide.css
  src/styles/slideBanner.css
  src/styles/tailwind.css
  src/vite-env.d.ts
Labels: HTML, CSS

#21 헤더, 푸터, 상품조회, 장바구니 페이지 마크업.
  public/cartArrowDown.png
  public/cartArrowUp.png
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/RootLayout.tsx
  src/pages/MyCart.tsx
  src/pages/MyOrder.tsx
Labels: HTML, CSS

#23 디테일 페이지 완성했습니다
  src/components/Brand/BrandIntroduce.tsx
  src/components/Brand/Logo.tsx
  src/components/Brand/Slogan.tsx
  src/components/Detail/DeliveryInformation.tsx
  src/components/Detail/DetailButton.tsx
  src/components/Detail/DetailImg.tsx
  src/components/Detail/DetailProductInformation.tsx
  src/components/Detail/DetailProductInformationList.tsx
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/Detail/ExchangeReturnInformation.tsx
  src/components/Detail/InformationTable.tsx
  src/components/Detail/InformationTableTr.tsx
  src/components/Detail/ProductInformation.tsx
  src/components/Detail/ProductOption.tsx
  src/components/Detail/ProductQnA.tsx
  src/components/Detail/ProductQuantity.tsx
  src/components/Detail/ProductReviews.tsx
  src/components/Home/BestItem.tsx
  src/components/Home/ReviewItem.tsx
  src/components/Home/ReviewSlide.tsx
  src/components/Home/SlideBanner.tsx
  src/components/PaginationLength.tsx
  src/components/PaginationNumber.tsx
  src/components/Shop/ProductContainer.tsx
  src/components/Shop/ProductItem.tsx
  src/pages/Brand.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/Shop.tsx
  src/styles/tailwind.css
  src/vite-env.d.ts
Labels: HTML, CSS

#27 [html/css] 상품 후기, 문의 페이지 구현, 푸터 스타일 정돈 등
  README.md
  public/noImage.gif
  src/layout/Footer.tsx
  src/pages/EditMember.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
  src/routes.tsx
Labels: HTML, CSS, 기능 추가

#28 장바구니, 주문조회, 마이페이지, 헤더 마크업 완성했습니다.
  public/myShoppingBoard.png
  public/myShoppingLike.png
  public/myShoppingOrder.png
  public/myShoppingProfile.png
  src/layout/Header.tsx
  src/pages/MyCart.tsx
  src/pages/MyOrder.tsx
  src/pages/MyShopping.tsx
Labels: HTML, CSS

#29 fix: 푸터 로고 컴포넌트 경로 수정
  src/layout/Footer.tsx
Labels: 버그 수정

#34 markup: 검색페이지 html/css 마크업
  src/layout/Header.tsx
  src/pages/Search.tsx
Labels: HTML, CSS

#36 [기능 구현] Login page 기능 추가, debounce 기능 추가
  src/pages/Login.tsx
  src/utils/debounce.tsx
Labels: React

#52 상품 Qna 페이지 수정중
  src/App.tsx
  src/components/PaginationLength.tsx
  src/components/PaginationNumber.tsx
  src/components/QnA,Review/Modal.tsx
  src/components/QnA,Review/ModalSearch.tsx
  src/components/QnA,Review/ModalSearchResult.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ModalSelectOrderResult.tsx
  src/components/QnA,Review/ProductSelect.tsx
  src/components/QnA,Review/Thead.tsx
  src/pages/Loading.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
  src/store/useData.ts
  src/styles/tailwind.css
  src/vite-env.d.ts
Labels: JavaScript, TypeScript, React, 기능 추가

#54 feat: Login페이지, Join페이지 기능추가
  src/layout/Header.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/Search.tsx
  src/store/useLogin.ts
  src/store/useUserInfo.ts
  src/utils/loginReg.tsx
Labels: JavaScript, React, 기능 추가

#55 [기능 구현] 메인 페이지, 상세 페이지, 쇼핑 페이지 기능 구현
  src/components/Detail/DetailProductInformation.tsx
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/ProductInformation.tsx
  src/components/Home/BestItem.tsx
  src/components/Home/SlideBanner.tsx
  src/components/Shop/ProductContainer.tsx
  src/components/Shop/ProductItem.tsx
  src/layout/Footer.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/Shop.tsx
  src/routes.tsx
Labels: CSS, React, 기능 추가

#58 header에 authorization 추가, header에 로그인 유저 값 보내기
  src/layout/Header.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
Labels: JavaScript, TypeScript, React, API

#61 Join페이지, 회원가입 기능 완성, login페이지 테스트코드 삭제
  src/pages/Join.tsx
  src/pages/Login.tsx
Labels: JavaScript, React, 기능 추가, API

#67 더미데이터 생성 후 렌더링중
  src/components/EachPost.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/components/QnA,Review/PageListOrder.tsx
  src/components/QnA,Review/RelatedPosts.tsx
  src/components/QnA,Review/ReviewProductItem.tsx
  src/components/QnA,Review/WriterButton.tsx
  src/pages/Community.tsx
  src/pages/Qna.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/WriteReview.tsx
  src/routes.tsx
  src/store/dummyData.ts
  src/store/useData.ts
  src/utils/getProductsData.tsx
  src/vite-env.d.ts
Labels: React, 기능 추가, API

#69 [기능 구현] 상세 페이지 상품별 옵션 렌더링 및 카운트 기능 구현, 개별 카운트 기능 구현 중
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/Detail/ProductQuantity.tsx
  src/styles/tailwind.css
Labels: React, 기능 추가

#70 Login page, Join page, EditPage
  src/layout/Header.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/store/useUserInfo.ts
  src/utils/loginReg.tsx
Labels: JavaScript, TypeScript, React, 기능 추가

#71 [기능 구현] 상세 페이지 옵션별 개별 카운트, 개별 금액, 총 금액 합산, 개수 합산 기능 구현 및 api 서버 리드미 설명
  README.md
  src/components/Detail/DetailImg.tsx
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/pages/Detail.tsx
Labels: CSS, React, 기능 추가

#72 EditMember 페이지, Join 페이지, Login 페이지 기능추가
  src/components/EditMember/phoneNumber.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/store/usePhoneNumber.ts
Labels: JavaScript, TypeScript, React, 기능 추가

#73 Qna, 리뷰페이지 기능 추가
  public/attachFile.png
  src/api/getData.ts
  src/components/Detail/DetailButton.tsx
  src/components/EachPost.tsx
  src/components/QnA,Review/CommentInput.tsx
  src/components/QnA,Review/CommentItem.tsx
  src/components/QnA,Review/FormAttachFile.tsx
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/FormTitleInput.tsx
  src/components/QnA,Review/Modal.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ModalSelectOrderResult.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/components/QnA,Review/PageListOrder.tsx
  src/components/QnA,Review/ProductSelect.tsx
  src/components/QnA,Review/RelatedPosts.tsx
  src/components/QnA,Review/RelatedPostsTbody.tsx
  src/components/QnA,Review/ReviewProductItem.tsx
  src/pages/Community.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
  src/store/dummyData.ts
  src/store/useComment.ts
  src/store/useData.ts
  src/utils/AUTH_TOKEN.ts
  src/vite-env.d.ts
Labels: JavaScript, TypeScript, 기능 추가, API

#74 chore: 토큰 값, 아이디값 함수로 수정
  src/pages/EditMember.tsx
Labels: JavaScript
