Repository likelion-plus/counting-stars-13, pull requests merged in 2023-12, with the labels that each got.

#82 Login page, join page, header page
  src/layout/Header.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
Labels: JavaScript, TypeScript, React, 기능 추가

#84 docs: 오류해결
  src/components/EachPost.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/pages/NoticeDetail.tsx
  src/store/dummyData.ts
Labels: JavaScript, TypeScript, React

#85 [기능 수정]
  src/components/EachPost.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/pages/NoticeDetail.tsx
  src/store/dummyData.ts
Labels: 버그 수정

#86 header 반응형으로 수정
  src/components/QnA,Review/ReviewProductItem.tsx
  src/layout/Header.tsx
  src/utils/getProductsData.tsx
Labels: CSS

#96 강사님 API 받아서 코드 수정중
  src/components/PageMap.tsx
  src/components/PaginationLength.tsx
  src/components/PaginationNumber.tsx
  src/components/QnA,Review/Modal.tsx
  src/components/QnA,Review/ModalSearch.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/components/QnA,Review/PageListOrder.tsx
  src/components/QnA,Review/ReviewProductItem.tsx
  src/pages/MyBoard.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/Search.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
  src/store/useData.ts
Labels: 버그 발생, HTML, CSS, JavaScript, TypeScript, React, 기능 추가, API

#102 EditMember, Join, Wish, Order 페이지 생성 및 수정
  src/components/EditMember/phoneNumber.tsx
  src/components/Login,Join/EmailCheckButton.tsx
  src/components/Wish/MiniButton.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyShopping.tsx
  src/pages/Order.tsx
  src/pages/Wish.tsx
  src/routes.tsx
Labels: HTML, CSS, JavaScript, TypeScript, React, 기능 추가

#103 [기능 구현] 장바구니 페이지 렌더링 및 합산, 개별, 전체 삭제 및 쇼핑 페이지 전체 목록 불러오기 등
  src/components/Detail/DetailProductSelect.tsx
  src/layout/Header.tsx
  src/pages/MyCart.tsx
  src/pages/Shop.tsx
  src/vite-env.d.ts
Labels: CSS, TypeScript, React, 기능 추가

#108 api 받아와서 코드 수정중
  src/components/Detail/DetailButton.tsx
  src/components/EachPost.tsx
  src/components/QnA,Review/CommentInput.tsx
  src/components/QnA,Review/CommentItem.tsx
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/Notice.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/components/QnA,Review/PageListOrder.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
  src/store/dummyData.ts
  src/store/useComment.ts
  src/store/useData.ts
  src/styles/tailwind.css
  src/utils/getProductsData.tsx
  src/vite-env.d.ts
Labels: JavaScript, TypeScript, React, 기능 추가, API

#109 EditMember, Order, MyOrder 마크업 및 기능구현 진행했습니다.
  src/components/EditMember/EditAddress.tsx
  src/pages/EditMember.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/store/useEditMemberInfo.ts
  src/store/useMyOrderInfo.ts
  src/store/useOrderUserInfo.ts
Labels: HTML, CSS, JavaScript, TypeScript, React, 기능 추가

#110 [기능 구현] 찜, 장바구니 담기 기능 구현, 마이 쇼핑 페이지 워딩 최적화 등
  src/components/Cart/CartGuide.tsx
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/pages/MyCart.tsx
  src/pages/MyShopping.tsx
  src/pages/Wish.tsx
  src/utils/HandleCart.tsx
  src/utils/HandleWish.tsx
Labels: 성능 향상, React, 기능 추가

#112 [기능구현] MyOrder 페이지 - 날짜별로 주문 목록 리스트로 출력
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/vite-env.d.ts
Labels: JavaScript, TypeScript, React, 기능 추가

#113 관리자 계정 조건문 추가
  src/components/Detail/DetailButton.tsx
  src/components/QnA,Review/CommentInput.tsx
  src/components/QnA,Review/CommentItem.tsx
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/components/QnA,Review/WriterButton.tsx
  src/pages/Login.tsx
  src/pages/MyBoard.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/WriteNotice.tsx
  src/routes.tsx
  src/store/useMyBoard.ts
Labels: HTML, CSS, JavaScript, 기능 추가, API

#115 [기능 구현] 장바구니, 찜 목록 기능 구현 및 헤더 푸터 최적화, axiosInstance 생성
  src/components/Detail/DetailProductSelect.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/pages/MyCart.tsx
  src/pages/MyShopping.tsx
  src/pages/Wish.tsx
  src/utils/HandleCart.tsx
  src/utils/HandleWish.tsx
  src/utils/axiosInstance.tsx
Labels: 성능 향상, React, 기능 추가, API

#118 검색페이지 들어갈시 생기는 오류 수정 및 자기 게시글 페이지 수정
  src/components/EachPost.tsx
  src/components/PaginationLength.tsx
  src/components/PaginationNumber.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/layout/Header.tsx
  src/pages/MyBoard.tsx
  src/pages/QnaDetail.tsx
  src/pages/ReviewDetail.tsx
  src/pages/Search.tsx
  src/store/useData.ts
  src/store/useMyBoard.ts
Labels: JavaScript, React, 기능 추가, API

#121 chore: MyOrder 페이지 타입 에러 해결
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/Login.tsx
  src/pages/MyOrder.tsx
  src/store/useMyOrderInfo.ts
Labels: TypeScript

#122 댓글무한렌더링 오류 수정
  src/components/EachPost.tsx
  src/components/QnA,Review/CommentInput.tsx
  src/components/QnA,Review/PageListOrder.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/store/useComment.ts
  src/vite-env.d.ts
Labels: JavaScript, TypeScript, 버그 수정

#123 feat: MyOrder 페이지, 주문 상태 필러팅 기능 구현
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/MyOrder.tsx
Labels: JavaScript, TypeScript, React, 기능 추가

#124 Login page, MyOrder page
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/Login.tsx
  src/pages/MyOrder.tsx
  src/store/useMyOrderInfo.ts
Labels: JavaScript, TypeScript, React, 기능 추가

#125 [기능 구현] 수정된 api에 맞춰 장바구니 담기 및 찜 기능 최적화
  src/components/Detail/DetailProductSelect.tsx
  src/components/Home/BestItem.tsx
  src/pages/MyCart.tsx
  src/pages/Shop.tsx
  src/pages/Wish.tsx
  src/vite-env.d.ts
Labels: TypeScript, React, API

#129 바뀐 API로 수정중
  public/completeIcon.png
  public/editIcon.png
  src/components/Detail/DetailButton.tsx
  src/components/QnA,Review/CommentInput.tsx
  src/components/QnA,Review/CommentItem.tsx
  src/components/QnA,Review/Notice.tsx
  src/components/QnA,Review/PageDetailTable.tsx
  src/components/QnA,Review/PageListOrder.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/WriteNotice.tsx
  src/store/useComment.ts
  src/styles/tailwind.css
  src/utils/setAnonymousName.ts
Labels: JavaScript, TypeScript, 기능 추가, API

#130 [기능 구현] 메인 페이지, 상세 페이지 후기 렌더링 및 물품 장바구니, 찜 위젯 기능 구현
  index.html
  src/components/Detail/DetailProductInformation.tsx
  src/components/Detail/InformationTable.tsx
  src/components/Detail/InformationTableTr.tsx
  src/components/Detail/ProductOption.tsx
  src/components/Detail/ProductQnA.tsx
  src/components/Detail/ProductReviews.tsx
  src/components/Home/ReviewItem.tsx
  src/components/Home/ReviewSlide.tsx
  src/components/Shop/ProductItem.tsx
  src/pages/Detail.tsx
  src/pages/MyCart.tsx
  src/pages/Wish.tsx
  src/utils/HandleWish.tsx
  src/vite-env.d.ts
Labels: 성능 향상, TypeScript, React, 기능 추가

#131 feat: MyOrder 페이지, 날짜 기간 기능 수정
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/MyOrder.tsx
Labels: JavaScript, React, 기능 추가

#135 feat: MyOrder 페이지 날짜 제한 기능
  package-lock.json
  package.json
  src/pages/MyOrder.tsx
Labels: React, 기능 추가

#136 [기능 구현] 주문하기 관련 작업 - 주문하기 페이지 물품 렌더링, 장바구니, 찜 페이지에서 주문 기능 구현
  src/pages/MyCart.tsx
  src/pages/Order.tsx
  src/pages/Wish.tsx
  src/store/useOrderSet.ts
Labels: React, 기능 추가

#142 [기능구현, 마크업]MyOrderDetail , MyOrder , loginPage
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/Login.tsx
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/routes.tsx
Labels: JavaScript, TypeScript, React, 기능 추가

#143 [기능 구현] 주문 페이지 삭제, 주문 기능 추가, 수정된 api에 맞게 수정, 장바구니 담기 및 취소 관련 오류 수정
  src/components/Detail/DetailProductOption.tsx
  src/pages/Order.tsx
  src/pages/Wish.tsx
  src/utils/HandleCart.tsx
  src/vite-env.d.ts
Labels: 성능 향상, TypeScript, React, 버그 수정, 기능 추가

#145 markup: MyOrder 페이지, html,css 마크업
  src/pages/MyOrderDetail.tsx
Labels: HTML, CSS

#147 몽고디비 이미지 경로 수정 및 토스트 에디터 placeHolder 추가
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/ProductSelect.tsx
Labels: JavaScript, API

#148 [기능 구현] 주문 내역 조회 리팩토링 및 소소한 수정, 메인 페이지 리뷰 노출 기준 적용
  src/components/Home/ReviewSlide.tsx
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/MyOrder.tsx
  src/store/useDeliveryState.ts
  src/store/useMyOrderInfo.ts
  src/vite-env.d.ts
Labels: 성능 향상, React

#149 api 주소 수정
  src/components/Detail/DetailButton.tsx
  src/components/QnA,Review/CommentInput.tsx
  src/components/QnA,Review/CommentItem.tsx
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/Modal.tsx
  src/components/QnA,Review/ModalSearch.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ModalSelectOrderResult.tsx
  src/components/QnA,Review/Notice.tsx
  src/components/QnA,Review/PassWordInput.tsx
  src/components/QnA,Review/ProductSelect.tsx
  src/components/QnA,Review/WriterButton.tsx
  src/pages/EditNotice.tsx
  src/pages/EditQna.tsx
  src/pages/MyBoard.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/Search.tsx
  src/pages/WriteNotice.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
Labels: API

#151 [기능 구현] MyOrderDetail 페이지, 주문 상세 리스트, 가격 출력
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/routes.tsx
Labels: JavaScript, TypeScript, React, 기능 추가

#152 [기능 구현] 백엔드 배포 맞춰 axios 인스턴스 생성 후 일괄 적용 및 장바구니 전체 선택 초깃값 적용
  .gitignore
  src/api/getData.ts
  src/components/Detail/DetailProductSelect.tsx
  src/components/Home/BestItem.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/MyCart.tsx
  src/pages/Order.tsx
  src/pages/Shop.tsx
  src/utils/HandleWish.tsx
  src/utils/axiosInstance.tsx
  src/vite-env.d.ts
Labels: 성능 향상, React, 기능 추가, API

#158 api 페이지네이션 및 qna 업로드 오류 수정
  src/components/QnA,Review/Modal.tsx
  src/components/QnA,Review/ModalSearch.tsx
  src/components/QnA,Review/Notice.tsx
  src/components/QueryPagination.tsx
  src/components/QueryPaginationLength.tsx
  src/layout/Header.tsx
  src/pages/EditQna.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Search.tsx
  src/pages/WriteQna.tsx
  src/store/useData.ts
Labels: TypeScript, 기능 추가, API

#159 [기능 구현] 주문 페이지 결제 기능 추가, 비로그인 시 장바구니 추가 불가, 재고 보여주기, 주문 처리 상태 정상 출력
  index.html
  src/components/Detail/DetailProductOption.tsx
  src/components/Home/ReviewSlide.tsx
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/store/useOrderUserInfo.ts
  src/utils/HandleCart.tsx
  src/vite-env.d.ts
  tsconfig.json
  types/global.d.ts
Labels: TypeScript, React, 버그 수정, 기능 추가

#160 [기능 구현] MyOrderDetail 페이지
  src/pages/Join.tsx
  src/pages/MyOrderDetail.tsx
  src/utils/useDeliveryState.tsx
Labels: JavaScript, TypeScript, React, 기능 추가

#163 [기능 구현] 주문 관련 커스텀 훅 생성 및 적용, 전역 상태 관리 immer 적용, 재고 부족 체크 및 안내
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/pages/MyCart.tsx
  src/pages/Wish.tsx
  src/store/useOrderSet.ts
  src/utils/useHandleOrder.ts
Labels: 성능 향상, React

#164 페이지네이션 구현 및 Qna 검색창 생성
  src/components/PageMap.tsx
  src/components/QnA,Review/ModalSearch.tsx
  src/components/QnA,Review/SearchBar.tsx
  src/layout/Header.tsx
  src/pages/Brand.tsx
  src/pages/Detail.tsx
  src/pages/MyBoard.tsx
  src/pages/MyCart.tsx
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/pages/MyShopping.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Order.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/Search.tsx
  src/pages/Shop.tsx
  src/pages/Wish.tsx
Labels: 기능 추가, API

#165 [2023.12.20 기능구현] develop브랜치에서 main브랜치로 merge
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/PageMap.tsx
  src/components/QnA,Review/ModalSearch.tsx
  src/components/QnA,Review/SearchBar.tsx
  src/layout/Header.tsx
  src/pages/Brand.tsx
  src/pages/Detail.tsx
  src/pages/MyBoard.tsx
  src/pages/MyCart.tsx
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/pages/MyShopping.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Order.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/Search.tsx
  src/pages/Shop.tsx
  src/pages/Wish.tsx
  src/store/useOrderSet.ts
  src/utils/useHandleOrder.ts
Labels: JavaScript, TypeScript, React, 기능 추가

#166 fix: build 문제 해결
  src/pages/MyCart.tsx
  src/pages/Wish.tsx
Labels: 버그 수정

#167 [2023.12.20 기능구현] build 문제 해결 후 develop브랜치에서 main브랜치로 merge
  src/pages/MyCart.tsx
  src/pages/Wish.tsx
Labels: 버그 수정

#169 [기능 구현] access 토큰 재발행 기능, MyOrderDetail 페이지, 옵션값, 주소값 설정
  src/App.tsx
  src/pages/MyOrderDetail.tsx
  src/utils/AUTH_TOKEN.ts
  src/utils/TokenRefresher.tsx
Labels: JavaScript, React, 기능 추가

#170 검색페이지 가격대 설정도 가능하게 수정
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ModalSelectOrderResult.tsx
  src/components/QnA,Review/ProductSelect.tsx
  src/components/QnA,Review/ReviewProductItem.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/Search.tsx
  src/pages/WriteReview.tsx
  src/styles/tailwind.css
Labels: JavaScript, API

#171 [기능 구현] 체크 박스 기능 커스텀 훅 생성 및 장바구니 담기 로직 변경 및 적용, 구매 시 장바구니에서 구매 작품 제거
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/Detail/ProductOption.tsx
  src/pages/MyCart.tsx
  src/pages/Order.tsx
  src/pages/Wish.tsx
  src/store/useCheckboxGroup.ts
  src/store/useOrderSet.ts
  src/utils/HandleCart.tsx
  src/utils/useHandleOrder.ts
  src/vite-env.d.ts
Labels: 성능 향상, TypeScript, React, 기능 추가, API

#172 [2023.12.21 기능구현] develop브랜치에서 main브랜치로 merge
  src/App.tsx
  src/components/Detail/DetailProductOption.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/Detail/ProductOption.tsx
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ModalSelectOrderResult.tsx
  src/components/QnA,Review/ProductSelect.tsx
  src/components/QnA,Review/ReviewProductItem.tsx
  src/pages/MyCart.tsx
  src/pages/MyOrderDetail.tsx
  src/pages/Order.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/Search.tsx
  src/pages/Wish.tsx
  src/pages/WriteReview.tsx
  src/store/useCheckboxGroup.ts
  src/store/useOrderSet.ts
  src/styles/tailwind.css
  src/utils/AUTH_TOKEN.ts
  src/utils/HandleCart.tsx
  src/utils/TokenRefresher.tsx
  src/utils/useHandleOrder.ts
  src/vite-env.d.ts
Labels: 성능 향상, JavaScript, TypeScript, React, 버그 수정, 기능 추가

#173 리뷰페이지 검색 기능 추가 및 검색페이지 가격설정 스타일 수정
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ReviewSearchBar.tsx
  src/pages/EditNotice.tsx
  src/pages/Review.tsx
  src/pages/Search.tsx
Labels: JavaScript, React, 기능 추가

#174 [기능 구현] 상세 페이지 상품 문의 출력, 상품 구매 시 로그인 체크 등
  src/components/Detail/DetailProductInformation.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/Detail/InformationTable.tsx
  src/components/Detail/InformationTableTr.tsx
  src/components/Detail/ProductQnA.tsx
  src/pages/Detail.tsx
  src/pages/MyCart.tsx
  src/pages/Order.tsx
  src/pages/Wish.tsx
  src/store/useHandleOrder.ts
Labels: 성능 향상, React, 기능 추가

#175 [기능구현] access토근 2차 만료시 자동 로그아웃 기능, MyOrder 페이지, option 값 추가
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/layout/Footer.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/utils/TokenRefresher.tsx
  src/utils/deliveryState.ts
  src/vite-env.d.ts
Labels: JavaScript, React, 기능 추가

#176 chore: 코드 정리
  src/pages/EditMember.tsx
  src/pages/MyOrderDetail.tsx
Labels: 문서

#177 fix: 주문조회 과다 출력 현상 수정, 주소 입력 시 모달 사라지기, 옵션 미선택 시 바로 구매 불가
  src/components/Detail/DetailProductSelect.tsx
  src/components/EditMember/EditAddress.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
Labels: 성능 향상, 버그 수정

#178 feat: 주문 시 주문인 정보 상세 전달 및 무통장 입금 삭제 등
  src/pages/Order.tsx
  src/store/useOrderUserInfo.ts
  src/utils/useDeliveryState.tsx
  src/vite-env.d.ts
Labels: TypeScript, React, 기능 추가

#179 [기능 구현] Qna 목록 버튼 오류 해결 및 주문상품 중복 객체 제거
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/pages/QnaDetail.tsx
Labels: JavaScript

#181 docs: 주소값이 존재하는 데이터에서만 주문상품 가져오기
  src/components/QnA,Review/ModalSelectOrder.tsx
Labels: JavaScript

#182 [2023.12.22] 중간 merge
  .env
  .env.development
  .env.local
  .env.production
  .gitignore
  package.json
  src/components/Detail/DetailProductInformation.tsx
  src/components/Detail/DetailProductResult.tsx
  src/components/Detail/DetailProductSelect.tsx
  src/components/Detail/InformationTable.tsx
  src/components/Detail/InformationTableTr.tsx
  src/components/Detail/ProductQnA.tsx
  src/components/EditMember/EditAddress.tsx
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/components/QnA,Review/ReviewSearchBar.tsx
  src/layout/Footer.tsx
  src/pages/Detail.tsx
  src/pages/EditMember.tsx
  src/pages/EditNotice.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyCart.tsx
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/pages/Order.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/Search.tsx
  src/pages/Wish.tsx
  src/store/useHandleOrder.ts
  src/store/useOrderUserInfo.ts
  src/utils/TokenRefresher.tsx
  src/utils/deliveryState.ts
  src/utils/useDeliveryState.tsx
  src/vite-env.d.ts
Labels: JavaScript, React, 기능 추가

#183 [기능 구현] 회원가입 이메일 중복 기능 추가
  src/components/Login,Join/EmailCheckButton.tsx
  src/pages/EditMember.tsx
  src/pages/MyOrderDetail.tsx
Labels: JavaScript, React, 기능 추가

#184 [2023.12.22] 회원가입 이메일 중복 기능 추가, 중간 merge
  src/components/Login,Join/EmailCheckButton.tsx
  src/pages/EditMember.tsx
  src/pages/MyOrderDetail.tsx
Labels: 문서

#185 docs; readme 작성
  README.md
  src/pages/Order.tsx
Labels: 문서

#187 [2023.12.22] 3차 merge
  README.md
  src/pages/MyOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/pages/Order.tsx
  src/store/useMyOrderInfo.ts
  src/vite-env.d.ts
Labels: JavaScript, React

#190 docs: 자식 아이디값 들어가던거 부모 아이디값으로 수정
  src/components/QnA,Review/ModalSelectOrder.tsx
Labels: 버그 수정

#191 [2023.12.22] 4차 merge
  src/components/QnA,Review/ModalSelectOrder.tsx
Labels: 버그 수정

#192 chore: MyOrderDetail 페이지, 전화번호, 배송메세지 추가
  src/pages/MyOrderDetail.tsx
  src/vite-env.d.ts
Labels: 기능 추가

#194 docs: parent 값 없으면 _id값
  src/components/QnA,Review/ModalSelectOrder.tsx
Labels: 버그 수정

#195 [2023.12.22] 5차 merge
  src/components/QnA,Review/ModalSelectOrder.tsx
  src/pages/MyOrderDetail.tsx
  src/vite-env.d.ts
Labels: 버그 수정

#196 fix: 주문할 내역 확인 api 변경, 주문 내역 filter 제거, 주소 기본값 변경
  src/components/EditMember/EditAddress.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/store/useOrderSet.ts
Labels: React

#197 [2023.12.22] 6차 merge
  src/components/EditMember/EditAddress.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/store/useOrderSet.ts
Labels: 버그 수정

#198 docs: 띄어쓰기 수정
  src/pages/MyBoard.tsx
Labels: HTML

#199 [2023.12.22] 7차 merge
  src/pages/MyBoard.tsx
Labels: 문서

#200 fix: placehorder 오류 수정
  src/components/QnA,Review/FormCkEditor.tsx
Labels: 버그 수정

#201 [2023.12.22] 8차 merge
  src/components/QnA,Review/FormCkEditor.tsx
Labels: 문서

#202 style: 주문하기 페이지 레이아웃 수정, 주소 필수 마크, 리드미 수정 등
  README.md
  src/components/EditMember/EditAddress.tsx
  src/pages/Order.tsx
  src/utils/TokenRefresher.tsx
Labels: CSS, 버그 수정

#203 chore: Join, Login, EditMember 페이지 수정
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/store/useJoinToLogin.ts
Labels: 문서, JavaScript, React

#204 [2023.12.22] 8차 merge
  README.md
  src/components/EditMember/EditAddress.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/Order.tsx
  src/store/useJoinToLogin.ts
  src/utils/TokenRefresher.tsx
Labels: 버그 수정

#205 fix: 찜에서 옵션 있는 상품 선택해서 장바구니 담을 시 두 개 담기는 현상 해결
  src/utils/HandleCart.tsx
Labels: 버그 수정

#206 [2023.12.22] 9차 merge
  src/utils/HandleCart.tsx
Labels: 버그 수정

#207 admin 계정 관리자로 표시
  src/pages/EditMember.tsx
  src/pages/Login.tsx
  src/pages/MyShopping.tsx
Labels: 기능 추가

#208 [2023.12.22] 10차 merge
  src/pages/EditMember.tsx
  src/pages/Login.tsx
  src/pages/MyShopping.tsx
Labels: 기능 추가

#212 [기능 추가] 상품 전체 목록 페이지네이션 구현 및 상품 모달 스타일 개선
  src/components/Detail/ProductOption.tsx
  src/pages/Shop.tsx
  src/utils/HandleCart.tsx
  src/utils/HandleWish.tsx
  src/vite-env.d.ts
Labels: 성능 향상, CSS, 기능 추가

#213 [2023.12.24] develop에서 main으로 merge
  src/components/Detail/ProductOption.tsx
  src/pages/Shop.tsx
  src/utils/HandleCart.tsx
  src/utils/HandleWish.tsx
  src/vite-env.d.ts
Labels: 기능 추가

#214 fix: swiper 경고 해결 및 절대 경로 지정 및 meta 정보 추가
  .env
  index.html
  src/components/Home/ReviewSlide.tsx
Labels: 성능 향상, CSS

#215 [2023.12.24] swiper 해결 및 성능 향상 후 develop에서 main으로 2차 merge
  .env
  index.html
  src/components/Home/ReviewSlide.tsx
Labels: 성능 향상, CSS

#220 [기능 구현] 주문하기 - 핸드폰 번호 숫자 아닌 것 입력 제한, 배송 메모 글자 제한, 게시판 글자 제한, 주소 readOnly 속성 부여 및 글자 제한
  src/components/EditMember/EditAddress.tsx
  src/components/OrderGuide.tsx
  src/components/QnA,Review/FormCkEditor.tsx
  src/components/QnA,Review/FormTitleInput.tsx
  src/pages/Order.tsx
Labels: 성능 향상, React, 기능 추가

#222 [refactor] 폴더명 수정, 생년월일 min,max 추가, form 태그 추가
  src/components/join/EmailCheckButton.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/utils/calculateDateYearsAgo.ts
Labels: 버그 수정, 기능 추가

#224 chore: EditMember, myOrder 폴더 이름 앞에 소문자로 변경
  src/components/editMember/EditAddress.tsx
  src/components/editMember/phoneNumber.tsx
  src/components/myOrder/OrderItem.tsx
  src/components/myOrder/OrderItemDetail.tsx
Labels: 버그 수정

#225 chore: 최종 이름 변경
  src/components/EditMember/EditAddress.tsx
  src/components/EditMember/phoneNumber.tsx
  src/components/MyOrder/OrderItem.tsx
  src/components/MyOrder/OrderItemDetail.tsx
Labels: 버그 수정

#223 [23.12.28] 메인 병합 - 폴더명 수정, 생년월일 min,max 추가, form 태그 추가
  src/components/editMember/EditAddress.tsx
  src/components/editMember/phoneNumber.tsx
  src/components/join/EmailCheckButton.tsx
  src/components/myOrder/OrderItem.tsx
  src/components/myOrder/OrderItemDetail.tsx
  src/pages/EditMember.tsx
  src/pages/Join.tsx
  src/pages/MyOrder.tsx
  src/pages/Order.tsx
  src/utils/calculateDateYearsAgo.ts
Labels: 버그 수정, 기능 추가

#226 피드백에 따른 폴더명 수정 및 import 수정
  src/components/brand/BrandIntroduce.tsx
  src/components/brand/Logo.tsx
  src/components/brand/Slogan.tsx
  src/components/qnaAndReview/CommentInput.tsx
  src/components/qnaAndReview/CommentItem.tsx
  src/components/qnaAndReview/ContentsViewer.tsx
  src/components/qnaAndReview/FormCkEditor.tsx
  src/components/qnaAndReview/FormTitleInput.tsx
  src/components/qnaAndReview/Modal.tsx
  src/components/qnaAndReview/ModalSearch.tsx
  src/components/qnaAndReview/ModalSearchResult.tsx
  src/components/qnaAndReview/ModalSelectOrder.tsx
  src/components/qnaAndReview/ModalSelectOrderResult.tsx
  src/components/qnaAndReview/Notice.tsx
  src/components/qnaAndReview/NoticeEachPost.tsx
  src/components/qnaAndReview/PageDetailTable.tsx
  src/components/qnaAndReview/PageDetailTitle.tsx
  src/components/qnaAndReview/PageListOrder.tsx
  src/components/qnaAndReview/ProductSelect.tsx
  src/components/qnaAndReview/ReviewProductItem.tsx
  src/components/qnaAndReview/ReviewSearchBar.tsx
  src/components/qnaAndReview/SearchBar.tsx
  src/components/qnaAndReview/Thead.tsx
  src/components/qnaAndReview/WriteButton.tsx
  src/components/qnaAndReview/WriterButton.tsx
  src/layout/Footer.tsx
  src/pages/Brand.tsx
  src/pages/EditNotice.tsx
  src/pages/EditQna.tsx
  src/pages/Home.tsx
  src/pages/MyBoard.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/WriteNotice.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
Labels: 문서

#227 [2023.12.31] main에 merge - 피드백에 따른 Qna,Review 폴더명 qnaAndReview로 수정
  src/components/brand/BrandIntroduce.tsx
  src/components/brand/Logo.tsx
  src/components/brand/Slogan.tsx
  src/components/qnaAndReview/CommentInput.tsx
  src/components/qnaAndReview/CommentItem.tsx
  src/components/qnaAndReview/ContentsViewer.tsx
  src/components/qnaAndReview/FormCkEditor.tsx
  src/components/qnaAndReview/FormTitleInput.tsx
  src/components/qnaAndReview/Modal.tsx
  src/components/qnaAndReview/ModalSearch.tsx
  src/components/qnaAndReview/ModalSearchResult.tsx
  src/components/qnaAndReview/ModalSelectOrder.tsx
  src/components/qnaAndReview/ModalSelectOrderResult.tsx
  src/components/qnaAndReview/Notice.tsx
  src/components/qnaAndReview/NoticeEachPost.tsx
  src/components/qnaAndReview/PageDetailTable.tsx
  src/components/qnaAndReview/PageDetailTitle.tsx
  src/components/qnaAndReview/PageListOrder.tsx
  src/components/qnaAndReview/ProductSelect.tsx
  src/components/qnaAndReview/ReviewProductItem.tsx
  src/components/qnaAndReview/ReviewSearchBar.tsx
  src/components/qnaAndReview/SearchBar.tsx
  src/components/qnaAndReview/Thead.tsx
  src/components/qnaAndReview/WriteButton.tsx
  src/components/qnaAndReview/WriterButton.tsx
  src/layout/Footer.tsx
  src/pages/Brand.tsx
  src/pages/EditNotice.tsx
  src/pages/EditQna.tsx
  src/pages/Home.tsx
  src/pages/MyBoard.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Qna.tsx
  src/pages/QnaDetail.tsx
  src/pages/Review.tsx
  src/pages/ReviewDetail.tsx
  src/pages/WriteNotice.tsx
  src/pages/WriteQna.tsx
  src/pages/WriteReview.tsx
Labels: 문서
